name: Migrate database
env:
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on: [push]
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn migrate:prod
